# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

alpha_cpp <- function(n, k, eps) {
    .Call(`_DoublingBF_alpha_cpp`, n, k, eps)
}

beta_cpp <- function(n, k, eps) {
    .Call(`_DoublingBF_beta_cpp`, n, k, eps)
}

hypergeom_mean <- function(m, n, Hn, eps, compute_a) {
    .Call(`_DoublingBF_hypergeom_mean`, m, n, Hn, eps, compute_a)
}

find_n0 <- function(eps) {
    .Call(`_DoublingBF_find_n0`, eps)
}

doubling_alg <- function(p, eps, n0 = -1L, max_iter = -1L, verbose = FALSE) {
    .Call(`_DoublingBF_doubling_alg`, p, eps, n0, max_iter, verbose)
}

logistic_cpp <- function(C, p) {
    .Call(`_DoublingBF_logistic_cpp`, C, p)
}

doubling_Huber_2019_iter_cpp <- function(C, i, eps, p) {
    .Call(`_DoublingBF_doubling_Huber_2019_iter_cpp`, C, i, eps, p)
}

